// Describes what is happening in our app

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";

export const LOAD_BOOKS_REQUEST = "LOAD_BOOKS_REQUEST";
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const LOAD_BOOKS_FAILURE = "LOAD_BOOKS_FAILURE";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const EDIT_BOOK_REQUEST = "EDIT_BOOK_REQUEST";
export const EDIT_BOOK_PROGRESS = "EDIT_BOOK_PROGRESS";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
